import { GoogleGenerativeAI } from '@google/generative-ai';
import * as dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';

// Load environment variables from .env
dotenv.config();

// Ensure Gemini API key is configured
const geminiApiKey = process.env.GEMINI_API_KEY;

if (!geminiApiKey) {
  console.error('\x1b[31mError: GEMINI_API_KEY environment variable is not set.\x1b[0m');
  console.error('Please create a \x1b[33m.env\x1b[0m file in the project root with your key:');
  console.error('GEMINI_API_KEY=your_api_key_here\n');
  process.exit(1);
}

// Parse command line arguments
const prUrl = process.argv[2];
if (!prUrl) {
  console.log('\x1b[36mUsage:\x1b[0m');
  console.log('  npm run test-local <github-pr-url>');
  console.log('\n\x1b[36mExample:\x1b[0m');
  console.log('  npm run test-local https://github.com/vitejs/vite/pull/16000\n');
  process.exit(1);
}

// Extract Owner, Repo, and PR number from URL
function parsePrUrl(url) {
  try {
    const parsed = new URL(url);
    if (parsed.hostname !== 'github.com') {
      throw new Error('Not a GitHub URL');
    }
    const pathParts = parsed.pathname.split('/').filter(Boolean);
    // Path should be like /owner/repo/pull/number
    if (pathParts[2] !== 'pull') {
      throw new Error('URL does not seem to be a Pull Request URL');
    }
    return {
      owner: pathParts[0],
      repo: pathParts[1],
      number: pathParts[3]
    };
  } catch (error) {
    console.error(`\x1b[31mError parsing PR URL: ${error.message}\x1b[0m`);
    process.exit(1);
  }
}

const { owner, repo, number } = parsePrUrl(prUrl);

async function fetchPrDetailsAndDiff(owner, repo, number) {
  const headers = {};
  if (process.env.GITHUB_TOKEN) {
    headers['Authorization'] = `token ${process.env.GITHUB_TOKEN}`;
  }
  
  console.log(`\x1b[34m[1/3]\x1b[0m Fetching details for PR #${number} from ${owner}/${repo}...`);
  
  // 1. Fetch metadata
  const metadataRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls/${number}`, { headers });
  if (!metadataRes.ok) {
    const errorText = await metadataRes.text();
    throw new Error(`Failed to fetch PR metadata (HTTP ${metadataRes.status}): ${errorText}`);
  }
  const metadata = await metadataRes.json();
  
  // 2. Fetch diff
  console.log(`\x1b[34m[2/3]\x1b[0m Fetching code diff...`);
  const diffHeaders = { ...headers, 'Accept': 'application/vnd.github.v3.diff' };
  const diffRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls/${number}`, { headers: diffHeaders });
  if (!diffRes.ok) {
    throw new Error(`Failed to fetch PR diff (HTTP ${diffRes.status})`);
  }
  const diff = await diffRes.text();
  
  return {
    title: metadata.title,
    description: metadata.body || 'No description provided.',
    diff
  };
}

async function main() {
  try {
    const { title, description, diff } = await fetchPrDetailsAndDiff(owner, repo, number);

    if (!diff || diff.trim() === '') {
      console.log('\x1b[33mNo diff content found. Skipping review.\x1b[0m');
      return;
    }

    console.log(`\x1b[34m[3/3]\x1b[0m Sending PR to Gemini AI model (gemini-3.5-flash)...`);
    
    const genAI = new GoogleGenerativeAI(geminiApiKey);
    const model = genAI.getGenerativeModel({ 
      model: 'gemini-3.5-flash',
      generationConfig: { temperature: 0.2 }
    });

    const prompt = `You are an elite software engineer and code reviewer.
Your job is to thoroughly review the Pull Request (PR) diff below, rate the updates out of 10, and provide constructive feedback.

PR Details:
- Title: ${title}
- Description: ${description}

Guidelines for Review:
1. Be polite, encouraging, and highly technical.
2. Give a clear **Rating out of 10** (e.g. 7.5/10) based on code quality, correctness, potential bugs, adherence to best practices, security, and performance.
3. Keep suggestions actionable and precise. Recommend lines to fix and write code examples where helpful.
4. If the PR has zero issues, congratulate the developer and explain why it's excellent.

Format your response in beautiful GitHub-Flavored Markdown. Use the following structured outline:

# 🤖 AI Pull Request Review & Rating

## 📊 Score: [X]/10
*[Add a brief 1-2 sentence high-level summary of the rating here]*

## 🔍 Key Changes Summarized
* [Bullet point list of primary changes]

## 🌟 The Good
* [What went well, clean patterns, or good decisions]

## 🛠️ Areas for Improvement
* [Specific, actionable feedback. Group by Severity: Critical, Warning, or Suggestion. Provide code snippets if recommending changes.]

---
*Review generated by Gemini AI.*`;

    const result = await model.generateContent([
      { text: prompt },
      { text: `Here is the code diff:\n\n\`\`\`diff\n${diff}\n\`\`\`` }
    ]);
    const response = await result.response;
    const reviewText = response.text();

    console.log('\n\x1b[32m=== Review Output ===\x1b[0m\n');
    console.log(reviewText);
    console.log('\n\x1b[32m=====================\x1b[0m\n');

  } catch (error) {
    console.error(`\x1b[31mError running review: ${error.message}\x1b[0m`);
    if (error.stack) {
      console.error(error.stack);
    }
  }
}

main();
